# Generated by Django 3.2.7 on 2021-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='', verbose_name='images/')),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='', verbose_name='images/')),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
